sudo: false
language: php
php:
  - 5.5

services:
  - mysql

before_script:
  - mysql -e 'create database miserend_testing character set utf8 collate utf8_unicode_ci;'
  - npm install
  - php composer.phar selfupdate
  - php composer.phar install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php install.php

script:
  - vendor/phpunit/phpunit/phpunit tests --configuration tests/phpunit.xml
 
after_success:
  - ${TRAVIS_BUILD_DIR}/deploy.sh

env:
  global:
  - MISEREND_WEBAPP_ENVIRONMENT=testing