version: "3.3"

services:
  mysql:
    container_name: mysql
    build:
      dockerfile: docker/Dockerfile.mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker:/tools
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: miserend
      MYSQL_USER: user
      MYSQL_PASSWORD: pw           
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","${MYSQL_USER}","-ppw"]
      timeout: 5s
      retries: 10
    networks:
      inner:
        aliases:
          - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      inner:
        aliases:
          - pma
  mailcatcher:
    image: dockage/mailcatcher
    container_name: mailcatcher
    ports:
    - 1025:1025
    - 1080:1080
    restart: on-failure:10
    networks:
      inner:
        aliases:
          - mailcatcher
  solr:
    image: solr:9.3
    container_name: solr
    ports:
     - 8983:8983
     - "9983:9983"
    entrypoint:      
      - solr
      - start
      - -c
      - -f     
    networks:
      inner:
        aliases:
          - solr
     
  miserend:
    container_name: miserend
    build:
      context: ./
      dockerfile: docker/Dockerfile.miserend
    command: ["./docker/entrypoint_miserend.sh"]
    volumes:
      - ./:/app
      - ./docker/apache2/miserend.conf:/etc/apache2/sites-enabled/miserend.conf
    ports:
      - "${MISEREND_PORT}:8000"
    networks:
      inner:
        aliases:
          - miserend
networks:
  inner:
    driver: bridge

volumes:
  db_data: {}